# Learning and Decision Making

## Laboratory 3: Partially observable Markov decision problems

In the end of the lab, you should submit all code/answers written in the tasks marked as "Activity n. XXX", together with the corresponding outputs and any replies to specific questions posed to the e-mail <adi.tecnico@gmail.com>. Make sure that the subject is of the form [&lt;group n.&gt;] LAB &lt;lab n.&gt;.

### 1. Modeling

Consider once again the POMDP problem from the homework and represented in the transition diagram below.

<img src="pomdp.png" width="400px">

Recall that:

* All transitions occur with probability 1 except those from state $A$, where the probabilities are indicated under the edge label.

* At each step, the agent makes an observation corresponding to the letter in the state designation. Such observation occurs with probability 1.

Consider throughout that $\gamma=0.9$.

---

#### Activity 1.        

Implement your POMDP in Python. In particular,

* Create a list with all the states;
* Create a list with all the actions;
* Create a list with all the observations
* For each action, define a `numpy` array with the corresponding transition probabilities;
* For each action, define a `numpy` array with the corresponding observation probabilities;
* Define a `numpy` array with the cost describing the problem.

The order for the states and actions used in the transition probability and cost matrices should match that in the lists of states and actions. 

**Note**: Don't forget to import `numpy`.

---

In [1]:
import numpy as np

# States
A = 0; B1 = 1; B2 = 2; C = 3; D = 4; E = 5; F = 6
X = (A, B1, B2, C, D, E, F)

Pa = np.zeros((7, 7))
Pa[A, B1] = 0.5
Pa[A, B2] = 0.5
Pa[B1, E] = 1
Pa[B2, F] = 1
Pa[C, B1] = 1
Pa[D, B2] = 1
Pa[E, A] = 1
Pa[F, A] = 1

Pb = np.zeros((7, 7))
Pb[A, B1] = 0.5
Pb[A, B2] = 0.5
Pb[B1, F] = 1
Pb[B2, E] = 1
Pb[C, B1] = 1
Pb[D, B2] = 1
Pb[E, A] = 1
Pb[F, A] = 1

Pc = np.zeros((7, 7))
Pc[A, B1] = 0.5
Pc[A, B2] = 0.5
Pc[B1, C] = 1
Pc[B2, D] = 1
Pc[C, B1] = 1
Pc[D, B2] = 1
Pc[E, A] = 1
Pc[F, A] = 1

Ps = [Pa, Pb, Pc]

# Observations
ZA = 0; ZB = 1; ZC = 2; ZD = 3; ZE = 4; ZF = 5
Z = (ZA, ZB, ZC, ZD, ZE, ZF)

Oa = np.zeros((7, 6))
Oa[A, ZA] = 1
Oa[B1, ZB] = 1
Oa[B2, ZB] = 1
Oa[C, ZC] = 1
Oa[D, ZD] = 1
Oa[E, ZE] = 1
Oa[F, ZF] = 1
Oc = Ob = Oa

# Actions
a = 0; b = 1; c = 2
A = (a, b, c)

C = np.ones((7, 3))
C[F, (a, b, c)] = 0

GAMMA = 0.9

print("Pa:")
print(Pa)
print("\nPb:")
print(Pb)
print("\nPc:")
print(Pc)
print("\nOa = Ob = Oc:")
print(Oa)
print("\nC:")
print(C)

Pa:
[[0.  0.5 0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  1. ]
 [0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0. ]]

Pb:
[[0.  0.5 0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1. ]
 [0.  0.  0.  0.  0.  1.  0. ]
 [0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0. ]]

Pc:
[[0.  0.5 0.5 0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0. ]
 [0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0. ]]

Oa = Ob = Oc:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

C:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]]


### 2. Sampling

You are now going to sample random trajectories of your POMDP and observe the impact it has on the corresponding belief.

---

#### Activity 2.

Generate a random POMDP trajectory using a uniformly random policy. In particular, from a random initial state $x_0$ generate:

1. A sequence of 10,000 states by selecting the actions uniformly at random;
2. The corresponding sequence of 10,000 actions;
3. The corresponding sequence of 10,000 observations.

---

In [7]:
STEPS = 10000

states = np.zeros((STEPS), dtype = np.int8)
actions = np.zeros((STEPS), dtype = np.int8)
observations = np.zeros((STEPS), dtype = np.int8)
currentState = np.random.choice(X)
states[0] = currentState
actions[0] = -1
observations[0] = -1
for i in range(1, STEPS):
    newAction = np.random.choice(A)
    newObservation = np.random.choice(Z, p = Oa[currentState])
    currentState = np.random.choice(X, p = Ps[newAction][currentState])
    states[i] = currentState
    actions[i] = newAction
    observations[i] = newObservation

print(states[:10])
print(actions[:10])
print(observations[:10])

[1 3 1 3 1 3 1 5 0 1]
[-1  2  1  2  2  2  0  0  2  0]
[-1  1  2  1  2  1  2  1  4  0]


---

#### Activity 3.

For the POMDP trajectory generated in Activity 2, compute the corresponding sequence of beliefs, assuming that the agent does not know its initial state. Report the resulting beliefs, ignoring duplicate beliefs or beliefs whose distance is smaller than $10^{-3}$.

**Note 1:** You may want to define a function `belief_update` that receives a belief, an action and an observation and returns the updated belief.

**Note 2:** To compute the distance between vectors, you may find useful `numpy`'s function `linalg.norm`.


---

In [3]:
# Insert your code here

### 3. Solution methods

In this section you are going to compare different non-exact solution methods.

---

#### Activity 4

Compute the solution for the underlying MDP and report the corresponding optimal policy and optimal cost-to-go. 

** Note:** You may reuse code from previous labs.

---

In [4]:
# Insert your code here

---

#### Activity 5

For each of the beliefs computed in Activity 3, compute the action prescribed by:

* The MLS heuristic;
* The AV heuristic;
* The Q-MDP heuristic.

---

In [5]:
# Insert your code here

---

#### Activity 6

Suppose that the optimal cost-to-go function for the POMDP can be represented using the $\alpha$-vectors



$$
\left\{
\begin{bmatrix}
8.39727208 \\
8.70168739 \\
7.80168739 \\
8.39727208 \\
8.39727208 \\
8.55748144 \\
7.55748144
\end{bmatrix},
\begin{bmatrix}
8.42645332 \\
8.70168739 \\
7.80168739 \\
8.02145332 \\
8.83145332 \\
8.55748144 \\
7.55748144
\end{bmatrix},
\begin{bmatrix}
8.42645332 \\
8.70168739 \\
7.80168739 \\
8.83145332 \\
8.02145332 \\
8.55748144 \\
7.55748144
\end{bmatrix},
\begin{bmatrix}
8.39727208 \\
7.80168739 \\
8.70168739 \\
8.39727208 \\
8.39727208 \\
8.55748144 \\
7.55748144
\end{bmatrix},
\begin{bmatrix}
8.42645332 \\
7.80168739 \\
8.70168739 \\
8.02145332 \\
8.83145332 \\
8.55748144 \\
7.55748144
\end{bmatrix},
\begin{bmatrix}
8.42645332 \\
7.80168739 \\
8.70168739 \\
8.83145332 \\
8.02145332 \\
8.55748144 \\
7.55748144
\end{bmatrix},
\begin{bmatrix}
8.39727208 \\
8.2192667  \\
8.2192667  \\
8.39727208 \\
8.39727208 \\
8.55748144 \\
7.55748144
\end{bmatrix},
\begin{bmatrix}
8.42645332 \\
8.2192667  \\
8.2192667  \\
8.02145332 \\
8.83145332 \\
8.55748144 \\
7.55748144
\end{bmatrix},
\begin{bmatrix}
8.42645332 \\
8.2192667  \\
8.2192667  \\
8.83145332 \\
8.02145332 \\
8.55748144 \\
7.55748144
\end{bmatrix},\right\}$$

where the first 3 vectors correspond to action $a$, the middle three vectors correspond to action $b$ and the last 3 vectors correspond to action $c$. Using the $\alpha$-vectors above, 

* Represent the the optimal cost-to-go function for all beliefs of the form $\mathbf{b}=[0, \epsilon, 1-\epsilon, 0, 0, 0, 0]$, with $\epsilon\in[0,1]$. 
* Compare the optimal policy with the MDP heuristics from Activity 5 in the beliefs computed in Activity 3.

** Note: ** Don't forget to import `matplotlib`, and use the magic `%matplotlib notebook`.

---

In [6]:
# Insert your code here

Insert your comments here