# Learning and Decision Making

## Laboratory 2: Markov decision problems

In the end of the lab, you should submit all code/answers written in the tasks marked as "Activity n. XXX", together with the corresponding outputs and any replies to specific questions posed to the e-mail <adi.tecnico@gmail.com>. Make sure that the subject is of the form [&lt;group n.&gt;] LAB &lt;lab n.&gt;.

### 1. Modeling

Consider once again the gridworld domain described in the Homework and which you modeled using a Markov decision process.

<img src="maze.png" width="200px">

Recall that:

* At each step, the agent may move in any of the four directions -- up, down, left and right. 
* Movement across a _grey_ cell division succeeds with a $0.8$ probability and fails with a $0.2$ probability. 
* Movements across colored cell divisions (blue or red) succeed with a $0.8$ probability _but only if the agent has the corresponding colored key_. Otherwise, they fail with probability $1$. 
* When the movement fails, the agent remains in the same cell. 
* To get a colored key, the agent simply needs to stand in the corresponding cell. 
* The goal of the agent is to reach the cell marked with **"G"**. 

**Throughout the lab, use $\gamma=0.99$.**

---

#### Activity 1.        

Implement your Markov decision process in Python. In particular,

* Create a list with all the states;
* Create a list with all the actions;
* For each action, define a `numpy` array with the corresponding transition probabilities;
* Define a `numpy`array with the costs. Make sure that:
    * The costs lie in the interval [0, 1]
    * The cost for standing in goal cell is minimal
    * The cost for standing in intermediate cells is maximal

The order for the states and actions used in the transition probability and cost matrices should match that in the lists of states and actions. 

**Note**: Don't forget to import `numpy`.

---

**Important Note**

We assigned each grid position of the environment, a letter, from A to G, such that, the newly drawn board is as presented below:
```
| A | B | E |  
    | C | F | G |  
    | D |  
```

B0 means in cell B with no keys; B1 in cell B with the red key; and B2 in cell B with both keys.

In [1]:
import numpy as np

B0 = 0; C0 = 1; E0 = 2; F0 = 3; B1 = 4; C1 = 5; D1 = 6; E1 = 7; F1 = 8;
A2 = 9; B2 = 10; C2 = 11; D2 = 12; E2 = 13; F2 = 14; G2 = 15
UP = 0; DOWN = 1; LEFT = 2; RIGHT = 3
GAMMA = 0.99

#States
X = ('B0', 'C0', 'E0', 'F0', 'B1', 'C1', 'D1', 'E1', 'F1', 'A2', 'B2', 'C2', 'D2', 'E2', 'F2', 'G2')
print("States: {}\n".format(X))

#Actions
A = ('U', 'D', 'L', 'R')
print("Actions: {}\n".format(A))

#Outcomes

#Action U(p)
PU = np.zeros((len(X), (len(X))))
PU[B0, B0] = 1
PU[C0, B0] = 0.8
PU[C0, C0] = 0.2
PU[E0, E0] = 1
PU[F0, E0] = 0.8
PU[F0, F0] = 0.2
PU[B1, B1] = 1
PU[C1, B1] = 0.8
PU[C1, C1] = 0.2
PU[D1, C1] = 0.8
PU[D1, D1] = 0.2
PU[E1, E1] = 1
PU[F1, E1] = 0.8
PU[F1, F1] = 0.2
PU[A2, A2] = 1
PU[B2, B2] = 1
PU[C2, B2] = 0.8
PU[C2, C2] = 0.2
PU[D2, C2] = 0.8
PU[D2, D2] = 0.2
PU[E2, E2] = 1
PU[F2, E2] = 0.8
PU[F2, F2] = 0.2
PU[G2, G2] = 1
print("Transition Probability Matrix for Up action: \n{}\n".format(PU))

#Action D(own)
PD = np.zeros((len(X), (len(X))))
PD[B0, B0] = 0.2
PD[B0, C0] = 0.8
PD[C0, C0] = 0.2
PD[C0, D1] = 0.8
PD[E0, E0] = 0.2
PD[E0, F0] = 0.8
PD[F0, F0] = 1
PD[B1, B1] = 0.2
PD[B1, C1] = 0.8
PD[C1, C1] = 0.2
PD[C1, D1] = 0.8
PD[D1, D1] = 1
PD[E1, E1] = 0.2
PD[E1, F1] = 0.8
PD[F1, F1] = 1
PD[A2, A2] = 1
PD[B2, B2] = 0.2
PD[B2, C2] = 0.8
PD[C2, C2] = 0.2
PD[C2, D2] = 0.8
PD[D2, D2] = 1
PD[E2, E2] = 0.2
PD[E2, F2] = 0.8
PD[F2, F2] = 1
PD[G2, G2] = 1
print("Transition Probability Matrix for Down action: \n{}\n".format(PD))

#Action L(eft)
PL = np.zeros((len(X), (len(X))))
PL[B0, B0] = 1
PL[C0, C0] = 1
PL[E0, B0] = 0.8
PL[E0, E0] = 0.2
PL[F0, C0] = 0.8
PL[F0, F0] = 0.2
PL[B1, B1] = 0.2
PL[B1, A2] = 0.8
PL[C1, C1] = 1
PL[D1, D1] = 1
PL[E1, B1] = 0.8
PL[E1, E1] = 0.2
PL[F1, C1] = 0.8
PL[F1, F1] = 0.2
PL[A2, A2] = 1
PL[B2, A2] = 0.8
PL[B2, B2] = 0.2
PL[C2, C2] = 1
PL[D2, D2] = 1
PL[E2, B2] = 0.8
PL[E2, E2] = 0.2
PL[F2, C2] = 0.8
PL[F2, F2] = 0.2
PL[G2, F2] = 0.8
PL[G2, G2] = 0.2
print("Transition Probability Matrix for Left action: \n{}\n".format(PL))

#Action R(ight)
PR = np.zeros((len(X), (len(X))))
PR[B0, B0] = 0.2
PR[B0, E0] = 0.8
PR[C0, C0] = 0.2
PR[C0, F0] = 0.8
PR[E0, E0] = 1
PR[F0, F0] = 1
PR[B1, B1] = 0.2
PR[B1, E1] = 0.8
PR[C1, C1] = 0.2
PR[C1, F1] = 0.8
PR[D1, D1] = 1
PR[E1, E1] = 1
PR[F1, F1] = 1
PR[A2, A2] = 0.2
PR[A2, B2] = 0.8
PR[B2, B2] = 0.2
PR[B2, E2] = 0.8
PR[C2, C2] = 0.2
PR[C2, F2] = 0.8
PR[D2, D2] = 1
PR[E2, E2] = 1
PR[F2, F2] = 0.2
PR[F2, G2] = 0.8
PR[G2, G2] = 1
print("Transition Probability Matrix for Right action: \n{}\n".format(PR))

Ps = [PU, PD, PL, PR]

#Cost
C = np.ones((len(X), len(A)))
C[G2, :] = 0
CU = C[:, UP].reshape((len(X), 1))
CD = C[:, DOWN].reshape((len(X), 1))
CL = C[:, LEFT].reshape((len(X), 1))
CR = C[:, RIGHT].reshape((len(X), 1))
Cs = [CU, CD, CL, CR]
print("Cost Function: \n{}\n".format(C))

States: ('B0', 'C0', 'E0', 'F0', 'B1', 'C1', 'D1', 'E1', 'F1', 'A2', 'B2', 'C2', 'D2', 'E2', 'F2', 'G2')

Actions: ('U', 'D', 'L', 'R')

Transition Probability Matrix for Up action: 
[[1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.8 0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.8 0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.8 0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.8 0.2 0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.8 0.2 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.8 0.2 0.  0.  0.  0. ]
 [0.  0.  0. 

### 2. Prediction

You are now going to evaluate a given policy, computing the corresponding cost-to-go.

---

#### Activity 2.

Describe the policy that, in each state $x$, always moves the agent to the cell closest to the goal (irrespectively of the number of keys in the agent's possession). If multiple such cells exist, the agent should select randomly between the two.

For example, suppose that the agent is in cell 2. It should then select randomly between the actions $D$ and $R$. Conversely, suppose that the agent is in cell 4. The knight should then select actions $R$ with probability 1.

**Note:** The policy should be described as a vector with as many rows as there are states and as many columns as there are actions, where the entry $(x,a)$ has the probability of selecting action $a$ in state $x$.

---

In [2]:
Pol = np.zeros((len(X), (len(A))))
Pol[B0] = [0, 0.5, 0, 0.5]
Pol[C0] = [0, 0, 0, 1]
Pol[E0] = [0, 1, 0, 0]
Pol[F0] = [0, 0, 0, 1]
Pol[B1] = [0, 0.5, 0, 0.5]
Pol[C1] = [0, 0, 0, 1]
Pol[D1] = [1, 0, 0, 0]
Pol[E1] = [0, 1, 0, 0]
Pol[F1] = [0, 0, 0, 1]
Pol[A2] = [0, 0, 0, 1]
Pol[B2] = [0, 0.5, 0, 0.5]
Pol[C2] = [0, 0, 0, 1]
Pol[D2] = [1, 0, 0, 0]
Pol[E2] = [0, 1, 0, 0]
Pol[F2] = [0, 0, 0, 1]
Pol[G2] = [1/3, 1/3, 0, 1/3]
print("Policy that in each state, moves the agent to the cell closest to the goal: \n{}\n".format(Pol))

Policy that in each state, moves the agent to the cell closest to the goal: 
[[0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         0.         1.        ]
 [0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.        ]
 [1.         0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         0.         1.        ]
 [0.         0.         0.         1.        ]
 [0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.        ]
 [1.         0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         0.         1.        ]
 [0.33333333 0.33333333 0.         0.33333333]]



---

#### Activity 3.

Compute the cost-to-go function $J^\pi$ associated with the policy from Activity 2.

---

In [3]:
Ppol = np.zeros((len(X), len(X)))
for i in range(len(Pol)):
    for j in range(len(Pol[0])):
        Ppol[i] += Ps[j][i] * Pol[i][j]

#print(Ppol)

Cpol = np.zeros((len(X), 1))
for i in range(len(Pol)):
    for j in range(len(Pol[0])):
        Cpol[i] += C[i][j] * Pol[i][j]

#print(Cpol)

Jpol = np.linalg.inv(np.eye(len(X)) - GAMMA * Ppol) @ Cpol
print(Jpol)


[[100.        ]
 [100.        ]
 [100.        ]
 [100.        ]
 [100.        ]
 [100.        ]
 [100.        ]
 [100.        ]
 [100.        ]
 [  4.89502117]
 [  3.69420073]
 [  2.47821842]
 [  3.69420073]
 [  2.47821842]
 [  1.24688279]
 [  0.        ]]


### 3. Control

In this section you are going to compare value and policy iteration, both in terms of time and number of iterations.

---

#### Activity 4

Show that the policy in Activity 3 is _not_ optimal: use value iteration to compute $J^*$ and show that $J^*\neq J^\pi$. Track the time and the number of iterations taken to compute $J^*$.

**Note 1:** Stop the algorithm when the error between iterations is smaller than $10^{-8}$.

**Note 2:** You may find useful the function ``time()`` from the module ``time``.

---

In [4]:
import time

MIN_ERR = 1e-8

J = np.zeros((len(X), 1))
err = 1
i = 0

start = time.time()
# Based on slide 62 of lec8.pdf:
while err > MIN_ERR:
    Qs = [Cs[i] + GAMMA * Ps[i] @ J for i in range(len(Ps))]
    Jnew = np.min(Qs, axis=0)
    err = np.linalg.norm(Jnew - J)
    i += 1
    J = Jnew
end = time.time()

print("J*:")
print(J)
print("Number of iterations:", i)
print("Elapsed time: %g seconds" % (end - start))

print("\nJ𝜋 is not optimal because it's different from J*.\nJ𝜋-J*:")
print(Jpol-J)
print("(The small negative values are caused by precision errors,"
      + " due to the iterative process of computing J*,"
      + "\nand should be ignored for comparison purposes.)")
print("As we can see, J* has a smaller cost-to-go than J𝜋 for every state.")

J*:
[[10.67823015]
 [ 9.55043002]
 [11.79196792]
 [10.67823015]
 [ 6.08086879]
 [ 7.25193028]
 [ 8.40839   ]
 [ 7.25193028]
 [ 8.40839   ]
 [ 4.89502117]
 [ 3.69420073]
 [ 2.47821842]
 [ 3.69420073]
 [ 2.47821842]
 [ 1.24688279]
 [ 0.        ]]
Number of iterations: 31
Elapsed time: 0.00224543 seconds

J𝜋 is not optimal because it's different from J*.
J𝜋-J*:
[[ 8.93217699e+01]
 [ 9.04495700e+01]
 [ 8.82080321e+01]
 [ 8.93217699e+01]
 [ 9.39191312e+01]
 [ 9.27480697e+01]
 [ 9.15916100e+01]
 [ 9.27480697e+01]
 [ 9.15916100e+01]
 [-1.77635684e-15]
 [-1.77635684e-15]
 [-8.88178420e-16]
 [-1.77635684e-15]
 [-8.88178420e-16]
 [-2.22044605e-16]
 [ 0.00000000e+00]]
(The small negative values are caused by precision errors, due to the iterative process of computing J*,
and should be ignored for comparison purposes.)
As we can see, J* has a smaller cost-to-go than J𝜋 for every state.


---

#### Activity 5

Compute once again the optimal policy now using policy iteration. Track the time and number of iterations taken and compare to those of Activity 4.

**Note:** If you find that numerical errors affect your computations (especially when comparing two values/arrays) you may use the `numpy` function `isclose` with adequately set absolute and relative tolerance parameters (e.g., $10^{-8}$).

---

In [5]:
# -- Insert your code here -- #

### 4. Simulation

Finally, in this section you will check whether the theoretical computations of the cost-to-go actually correspond to the cost incurred by an agent following a policy.

---

#### Activity 6

Suppose that the agent is where depicted in Fig. 1, and consider the situations (i) where it has no keys; (ii) where it has only the red key; (iii) where it has both keys. For each of the three situations,  

* Generate **100** trajectories of 10,000 steps each, following the optimal policy for the MDP. 
* For each trajectory, compute the accumulated (discounted) cost. 
* Compute the average cost over the 100 trajectories.
* Compare the resulting value with that computed in Activity 4. 

** Note:** The simulation may take a bit of time, don't despair ☺️.

---

In [6]:
# -- Insert your code here -- #